### ISSUE TITLE
driver: support multiple motion groups

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#9]
Subtasks:
- [ ] report state of all motion groups with `ros_state` (was: #4)
- [ ] add support for `JOINT_FEEDBACK` messages to `ros_state` (was: #5)
- [ ] `ros_relay` only controls first motion group (was: #6)
- [ ] add support for `JOINT_TRAJ_PT_FULL` message to `ros_relay` (was: #7)

**Comment by gavanderhoorn** [comment]
This will not be addressed any more in `fanuc_driver` - other developments will take priority.

Community contributions will be accepted though.

Closing.
